### ISSUE TITLE
Say hello

### ISSUE THREAD

**Issue by younthu** [marsohod4you/btc-fpga-miner#1]
Hello, 

i'm interested in breaking bitcoin wallet with hardware. while i am looking for some opensourced fpga solution, i found your project, it looks great!

I'm a software engineer, no experience in FPGA. 
Could you give me some hints for where should i start from? 
Or, if possible, can i join your project, try to fix some bug for you, or contribute some enhancement?

Thank you very much!

**Comment by marsohod4you** [comment]
hello
What do You mean under "break bitcoin wallet"?
Do You want to find a method to generate a wallet which already has money?
I do not believe this is possible with FPGA..
Nick


ср, 18 нояб. 2020 г. в 06:45, Andrew Yang <notifications@github.com>:

**Comment by younthu** [comment]
Thank you very much!
